import React from 'react';
import ReactDOM from 'react-dom/client';
import { Hono } from 'hono';
import { serveStatic } from 'hono/deno';
import { TanStackRouter } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen'; // This will be generated by TanStack Router

// Create a new Hono app
const app = new Hono();

// Create a new router instance
const router = new TanStackRouter({ routeTree });

// Serve static files from the public directory
app.use('/static/*', serveStatic({ root: './public/' }));

// Use the router to render the app
app.get('*', (c) => {
  const root = ReactDOM.createRoot(document.getElementById('root')!);
  root.render(
    <React.StrictMode>
      <TanStackRouter router={router} />
    </React.StrictMode>
  );
  return c.html(''); // Return empty HTML as React will render the content
});

// Check if running in a browser environment before rendering
if (typeof document !== 'undefined') {
  const rootElement = document.getElementById('root');
  if (rootElement) {
    const root = ReactDOM.createRoot(rootElement);
    root.render(
      <React.StrictMode>
        <TanStackRouter router={router} />
      </React.StrictMode>
    );
  } else {
    console.error("Target element with ID 'root' not found in the DOM.");
  }
}

export default app;
